#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/migration/db.changelog-master.yaml

server:
  port: 8083

auth:
  jwt:
    secret: MySecureSecretKeyWhichICanUseOnlyAtDevelopmentModeNotInProduction
    expiration-ms: 1000
  admin-key: rnq-HcE-WRV-UhT